"""
Pydantic models for API requests and responses.
"""

from .drone import (
    Position,
    Velocity,
    DroneStatusResponse,
    FleetStatusResponse,
    MoveRequest,
    GotoHouseRequest,
    GotoHouseResponse,
    RotateRequest,
    FaceTargetRequest,
    PhotoRequest,
    PhotoResponse,
    TakeoffRequest,
    AltitudeRequest,
    HouseInfo,
    HousesResponse,
)

from .mission import (
    FormationRequest,
    FormationResponse,
    SearchRequest,
    SearchResponse,
    FollowLeaderRequest,
    FollowLeaderResponse,
    FleetMoveRequest,
    WaypointModel,
    CreateMissionRequest,
    PlanWaypointMissionRequest,
    PlanSurveyMissionRequest,
    PlanInspectionMissionRequest,
    MissionResponse,
    MissionListResponse,
    GeofenceRequest,
    GeofenceResponse,
    NoFlyZoneRequest,
    NoFlyZoneResponse,
    EmergencyResponse,
    ValidationResponse,
)

__all__ = [
    # Drone models
    "Position",
    "Velocity",
    "DroneStatusResponse",
    "FleetStatusResponse",
    "MoveRequest",
    "GotoHouseRequest",
    "GotoHouseResponse",
    "RotateRequest",
    "FaceTargetRequest",
    "PhotoRequest",
    "PhotoResponse",
    "TakeoffRequest",
    "AltitudeRequest",
    "HouseInfo",
    "HousesResponse",
    # Fleet/Mission models
    "FormationRequest",
    "FormationResponse",
    "SearchRequest",
    "SearchResponse",
    "FollowLeaderRequest",
    "FollowLeaderResponse",
    "FleetMoveRequest",
    "WaypointModel",
    "CreateMissionRequest",
    "PlanWaypointMissionRequest",
    "PlanSurveyMissionRequest",
    "PlanInspectionMissionRequest",
    "MissionResponse",
    "MissionListResponse",
    "GeofenceRequest",
    "GeofenceResponse",
    "NoFlyZoneRequest",
    "NoFlyZoneResponse",
    "EmergencyResponse",
    "ValidationResponse",
]
